name: Deploy Fit Hero AI Service to Azure App Service

on:
  push:
    branches: [ main, feat/ai-service-migrate-to-azure ]
    paths: [ 'fit-hero-ai-service/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'fit-hero-ai-service/**' ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: fit-hero-ai-service-uk    # Correct Azure app name from CLI
  AZURE_WEBAPP_PACKAGE_PATH: './fit-hero-ai-service'  # Set this to the path to your web app project
  PYTHON_VERSION: '3.11'                   # Set this to the Python version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          source venv/bin/activate
          pip install -r requirements.txt
          
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          zip -r ../fit-hero-ai-service.zip . -x venv/\*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            fit-hero-ai-service.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          
      - name: Unzip artifact for deployment
        run: unzip fit-hero-ai-service.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: '.'
